<?php

/*
 * Copyright 2011-2017 Ning, Inc.
 * Copyright 2014 Groupon, Inc.
 * Copyright 2014 The Billing Project, LLC
 *
 * The Billing Project licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
namespace Killbill\Client\Type;


/*
 *                       DO NOT EDIT!!!
 *    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)
 */


class AccountAttributes extends \Killbill\Client\Resource {
  protected $accountId = null;
  protected $name = null;
  protected $firstNameLength = null;
  protected $externalKey = null;
  protected $email = null;
  protected $billCycleDayLocal = null;
  protected $currency = null;
  protected $parentAccountId = null;
  protected $isPaymentDelegatedToParent = null;
  protected $paymentMethodId = null;
  protected $timeZone = null;
  protected $address1 = null;
  protected $address2 = null;
  protected $postalCode = null;
  protected $company = null;
  protected $city = null;
  protected $state = null;
  protected $country = null;
  protected $locale = null;
  protected $phone = null;
  protected $notes = null;
  protected $isMigrated = null;
  protected $isNotifiedForInvoices = null;
  protected $accountBalance = null;
  protected $accountCBA = null;
  protected $auditLogs = null;

  public function setAccountId ($accountId) {
    $this->accountId = $accountId;
  }

  public function getAccountId () {
    return $this->accountId;
  }

  public function setName ($name) {
    $this->name = $name;
  }

  public function getName () {
    return $this->name;
  }

  public function setFirstNameLength ($firstNameLength) {
    $this->firstNameLength = $firstNameLength;
  }

  public function getFirstNameLength () {
    return $this->firstNameLength;
  }

  public function setExternalKey ($externalKey) {
    $this->externalKey = $externalKey;
  }

  public function getExternalKey () {
    return $this->externalKey;
  }

  public function setEmail ($email) {
    $this->email = $email;
  }

  public function getEmail () {
    return $this->email;
  }

  public function setBillCycleDayLocal ($billCycleDayLocal) {
    $this->billCycleDayLocal = $billCycleDayLocal;
  }

  public function getBillCycleDayLocal () {
    return $this->billCycleDayLocal;
  }

  public function setCurrency ($currency) {
    $this->currency = $currency;
  }

  public function getCurrency () {
    return $this->currency;
  }

  public function setParentAccountId ($parentAccountId) {
    $this->parentAccountId = $parentAccountId;
  }

  public function getParentAccountId () {
    return $this->parentAccountId;
  }

  public function setIsPaymentDelegatedToParent ($isPaymentDelegatedToParent) {
    $this->isPaymentDelegatedToParent = $isPaymentDelegatedToParent;
  }

  public function getIsPaymentDelegatedToParent () {
    return $this->isPaymentDelegatedToParent;
  }

  public function setPaymentMethodId ($paymentMethodId) {
    $this->paymentMethodId = $paymentMethodId;
  }

  public function getPaymentMethodId () {
    return $this->paymentMethodId;
  }

  public function setTimeZone ($timeZone) {
    $this->timeZone = $timeZone;
  }

  public function getTimeZone () {
    return $this->timeZone;
  }

  public function setAddress1 ($address1) {
    $this->address1 = $address1;
  }

  public function getAddress1 () {
    return $this->address1;
  }

  public function setAddress2 ($address2) {
    $this->address2 = $address2;
  }

  public function getAddress2 () {
    return $this->address2;
  }

  public function setPostalCode ($postalCode) {
    $this->postalCode = $postalCode;
  }

  public function getPostalCode () {
    return $this->postalCode;
  }

  public function setCompany ($company) {
    $this->company = $company;
  }

  public function getCompany () {
    return $this->company;
  }

  public function setCity ($city) {
    $this->city = $city;
  }

  public function getCity () {
    return $this->city;
  }

  public function setState ($state) {
    $this->state = $state;
  }

  public function getState () {
    return $this->state;
  }

  public function setCountry ($country) {
    $this->country = $country;
  }

  public function getCountry () {
    return $this->country;
  }

  public function setLocale ($locale) {
    $this->locale = $locale;
  }

  public function getLocale () {
    return $this->locale;
  }

  public function setPhone ($phone) {
    $this->phone = $phone;
  }

  public function getPhone () {
    return $this->phone;
  }

  public function setNotes ($notes) {
    $this->notes = $notes;
  }

  public function getNotes () {
    return $this->notes;
  }

  public function setIsMigrated ($isMigrated) {
    $this->isMigrated = $isMigrated;
  }

  public function getIsMigrated () {
    return $this->isMigrated;
  }

  public function setIsNotifiedForInvoices ($isNotifiedForInvoices) {
    $this->isNotifiedForInvoices = $isNotifiedForInvoices;
  }

  public function getIsNotifiedForInvoices () {
    return $this->isNotifiedForInvoices;
  }

  public function setAccountBalance ($accountBalance) {
    $this->accountBalance = $accountBalance;
  }

  public function getAccountBalance () {
    return $this->accountBalance;
  }

  public function setAccountCBA ($accountCBA) {
    $this->accountCBA = $accountCBA;
  }

  public function getAccountCBA () {
    return $this->accountCBA;
  }

  public function setAuditLogs ($auditLogs) {
    $this->auditLogs = $auditLogs;
  }

  public function getAuditLogs () {
    return $this->auditLogs;
  }

}
