<?php

/*
 * Copyright 2011-2017 Ning, Inc.
 * Copyright 2014 Groupon, Inc.
 * Copyright 2014 The Billing Project, LLC
 *
 * The Billing Project licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
namespace Killbill\Client\Type;


/*
 *                       DO NOT EDIT!!!
 *    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)
 */


class BillingExceptionAttributes extends \Killbill\Client\Resource {
  protected $className = null;
  protected $code = null;
  protected $message = null;
  protected $causeClassName = null;
  protected $causeMessage = null;
  protected $stackTrace = null;

  public function setClassName ($className) {
    $this->className = $className;
  }

  public function getClassName () {
    return $this->className;
  }

  public function setCode ($code) {
    $this->code = $code;
  }

  public function getCode () {
    return $this->code;
  }

  public function setMessage ($message) {
    $this->message = $message;
  }

  public function getMessage () {
    return $this->message;
  }

  public function setCauseClassName ($causeClassName) {
    $this->causeClassName = $causeClassName;
  }

  public function getCauseClassName () {
    return $this->causeClassName;
  }

  public function setCauseMessage ($causeMessage) {
    $this->causeMessage = $causeMessage;
  }

  public function getCauseMessage () {
    return $this->causeMessage;
  }

  public function setStackTrace ($stackTrace) {
    $this->stackTrace = $stackTrace;
  }

  public function getStackTrace () {
    return $this->stackTrace;
  }

}
