<?php

/*
 * Copyright 2011-2017 Ning, Inc.
 * Copyright 2014 Groupon, Inc.
 * Copyright 2014 The Billing Project, LLC
 *
 * The Billing Project licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
namespace Killbill\Client\Type;


/*
 *                       DO NOT EDIT!!!
 *    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)
 */


class HostedPaymentPageFormDescriptorAttributes extends \Killbill\Client\Resource {
  protected $kbAccountId = null;
  protected $formMethod = null;
  protected $formUrl = null;
  protected $formFields = null;
  protected $properties = null;

  public function setKbAccountId ($kbAccountId) {
    $this->kbAccountId = $kbAccountId;
  }

  public function getKbAccountId () {
    return $this->kbAccountId;
  }

  public function setFormMethod ($formMethod) {
    $this->formMethod = $formMethod;
  }

  public function getFormMethod () {
    return $this->formMethod;
  }

  public function setFormUrl ($formUrl) {
    $this->formUrl = $formUrl;
  }

  public function getFormUrl () {
    return $this->formUrl;
  }

  public function setFormFields ($formFields) {
    $this->formFields = $formFields;
  }

  public function getFormFields () {
    return $this->formFields;
  }

  public function setProperties ($properties) {
    $this->properties = $properties;
  }

  public function getProperties () {
    return $this->properties;
  }

}
