<?php

/*
 * Copyright 2011-2017 Ning, Inc.
 * Copyright 2014 Groupon, Inc.
 * Copyright 2014 The Billing Project, LLC
 *
 * The Billing Project licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
namespace Killbill\Client\Type;


/*
 *                       DO NOT EDIT!!!
 *    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)
 */


class InvoiceAttributes extends \Killbill\Client\Resource {
  protected $amount = null;
  protected $currency = null;
  protected $status = null;
  protected $creditAdj = null;
  protected $refundAdj = null;
  protected $invoiceId = null;
  protected $invoiceDate = null;
  protected $targetDate = null;
  protected $invoiceNumber = null;
  protected $balance = null;
  protected $accountId = null;
  protected $externalBundleKeys = null;
  protected $credits = null;
  protected $items = null;
  protected $isParentInvoice = null;
  protected $auditLogs = null;

  public function setAmount ($amount) {
    $this->amount = $amount;
  }

  public function getAmount () {
    return $this->amount;
  }

  public function setCurrency ($currency) {
    $this->currency = $currency;
  }

  public function getCurrency () {
    return $this->currency;
  }

  public function setStatus ($status) {
    $this->status = $status;
  }

  public function getStatus () {
    return $this->status;
  }

  public function setCreditAdj ($creditAdj) {
    $this->creditAdj = $creditAdj;
  }

  public function getCreditAdj () {
    return $this->creditAdj;
  }

  public function setRefundAdj ($refundAdj) {
    $this->refundAdj = $refundAdj;
  }

  public function getRefundAdj () {
    return $this->refundAdj;
  }

  public function setInvoiceId ($invoiceId) {
    $this->invoiceId = $invoiceId;
  }

  public function getInvoiceId () {
    return $this->invoiceId;
  }

  public function setInvoiceDate ($invoiceDate) {
    $this->invoiceDate = $invoiceDate;
  }

  public function getInvoiceDate () {
    return $this->invoiceDate;
  }

  public function setTargetDate ($targetDate) {
    $this->targetDate = $targetDate;
  }

  public function getTargetDate () {
    return $this->targetDate;
  }

  public function setInvoiceNumber ($invoiceNumber) {
    $this->invoiceNumber = $invoiceNumber;
  }

  public function getInvoiceNumber () {
    return $this->invoiceNumber;
  }

  public function setBalance ($balance) {
    $this->balance = $balance;
  }

  public function getBalance () {
    return $this->balance;
  }

  public function setAccountId ($accountId) {
    $this->accountId = $accountId;
  }

  public function getAccountId () {
    return $this->accountId;
  }

  public function setExternalBundleKeys ($externalBundleKeys) {
    $this->externalBundleKeys = $externalBundleKeys;
  }

  public function getExternalBundleKeys () {
    return $this->externalBundleKeys;
  }

  public function setCredits ($credits) {
    $this->credits = $credits;
  }

  public function getCredits () {
    return $this->credits;
  }

  public function setItems ($items) {
    $this->items = $items;
  }

  public function getItems () {
    return $this->items;
  }

  public function setIsParentInvoice ($isParentInvoice) {
    $this->isParentInvoice = $isParentInvoice;
  }

  public function getIsParentInvoice () {
    return $this->isParentInvoice;
  }

  public function setAuditLogs ($auditLogs) {
    $this->auditLogs = $auditLogs;
  }

  public function getAuditLogs () {
    return $this->auditLogs;
  }

}
