<?php

/*
 * Copyright 2011-2017 Ning, Inc.
 * Copyright 2014 Groupon, Inc.
 * Copyright 2014 The Billing Project, LLC
 *
 * The Billing Project licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
namespace Killbill\Client\Type;


/*
 *                       DO NOT EDIT!!!
 *    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)
 */


class NotificationAttributes extends \Killbill\Client\Resource {
  protected $eventType = null;
  protected $accountId = null;
  protected $objectType = null;
  protected $objectId = null;

  public function setEventType ($eventType) {
    $this->eventType = $eventType;
  }

  public function getEventType () {
    return $this->eventType;
  }

  public function setAccountId ($accountId) {
    $this->accountId = $accountId;
  }

  public function getAccountId () {
    return $this->accountId;
  }

  public function setObjectType ($objectType) {
    $this->objectType = $objectType;
  }

  public function getObjectType () {
    return $this->objectType;
  }

  public function setObjectId ($objectId) {
    $this->objectId = $objectId;
  }

  public function getObjectId () {
    return $this->objectId;
  }

}
