<?php

/*
 * Copyright 2011-2017 Ning, Inc.
 * Copyright 2014 Groupon, Inc.
 * Copyright 2014 The Billing Project, LLC
 *
 * The Billing Project licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
namespace Killbill\Client\Type;


/*
 *                       DO NOT EDIT!!!
 *    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)
 */


class OverdueStateConfigAttributes extends \Killbill\Client\Resource {
  protected $name = null;
  protected $isClearState = null;
  protected $condition = null;
  protected $externalMessage = null;
  protected $blockChanges = null;
  protected $disableEntitlement = null;
  protected $subscriptionCancellationPolicy = null;
  protected $autoReevaluationIntervalDays = null;

  public function setName ($name) {
    $this->name = $name;
  }

  public function getName () {
    return $this->name;
  }

  public function setIsClearState ($isClearState) {
    $this->isClearState = $isClearState;
  }

  public function getIsClearState () {
    return $this->isClearState;
  }

  public function setCondition ($condition) {
    $this->condition = $condition;
  }

  public function getCondition () {
    return $this->condition;
  }

  public function setExternalMessage ($externalMessage) {
    $this->externalMessage = $externalMessage;
  }

  public function getExternalMessage () {
    return $this->externalMessage;
  }

  public function setBlockChanges ($blockChanges) {
    $this->blockChanges = $blockChanges;
  }

  public function getBlockChanges () {
    return $this->blockChanges;
  }

  public function setDisableEntitlement ($disableEntitlement) {
    $this->disableEntitlement = $disableEntitlement;
  }

  public function getDisableEntitlement () {
    return $this->disableEntitlement;
  }

  public function setSubscriptionCancellationPolicy ($subscriptionCancellationPolicy) {
    $this->subscriptionCancellationPolicy = $subscriptionCancellationPolicy;
  }

  public function getSubscriptionCancellationPolicy () {
    return $this->subscriptionCancellationPolicy;
  }

  public function setAutoReevaluationIntervalDays ($autoReevaluationIntervalDays) {
    $this->autoReevaluationIntervalDays = $autoReevaluationIntervalDays;
  }

  public function getAutoReevaluationIntervalDays () {
    return $this->autoReevaluationIntervalDays;
  }

}
