<?php

/*
 * Copyright 2011-2017 Ning, Inc.
 * Copyright 2014 Groupon, Inc.
 * Copyright 2014 The Billing Project, LLC
 *
 * The Billing Project licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
namespace Killbill\Client\Type;


/*
 *                       DO NOT EDIT!!!
 *    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)
 */


class PaymentAttemptAttributes extends \Killbill\Client\Resource {
  protected $accountId = null;
  protected $paymentMethodId = null;
  protected $paymentExternalKey = null;
  protected $transactionId = null;
  protected $transactionExternalKey = null;
  protected $transactionType = null;
  protected $effectiveDate = null;
  protected $stateName = null;
  protected $amount = null;
  protected $currency = null;
  protected $pluginName = null;
  protected $pluginProperties = null;
  protected $auditLogs = null;

  public function setAccountId ($accountId) {
    $this->accountId = $accountId;
  }

  public function getAccountId () {
    return $this->accountId;
  }

  public function setPaymentMethodId ($paymentMethodId) {
    $this->paymentMethodId = $paymentMethodId;
  }

  public function getPaymentMethodId () {
    return $this->paymentMethodId;
  }

  public function setPaymentExternalKey ($paymentExternalKey) {
    $this->paymentExternalKey = $paymentExternalKey;
  }

  public function getPaymentExternalKey () {
    return $this->paymentExternalKey;
  }

  public function setTransactionId ($transactionId) {
    $this->transactionId = $transactionId;
  }

  public function getTransactionId () {
    return $this->transactionId;
  }

  public function setTransactionExternalKey ($transactionExternalKey) {
    $this->transactionExternalKey = $transactionExternalKey;
  }

  public function getTransactionExternalKey () {
    return $this->transactionExternalKey;
  }

  public function setTransactionType ($transactionType) {
    $this->transactionType = $transactionType;
  }

  public function getTransactionType () {
    return $this->transactionType;
  }

  public function setEffectiveDate ($effectiveDate) {
    $this->effectiveDate = $effectiveDate;
  }

  public function getEffectiveDate () {
    return $this->effectiveDate;
  }

  public function setStateName ($stateName) {
    $this->stateName = $stateName;
  }

  public function getStateName () {
    return $this->stateName;
  }

  public function setAmount ($amount) {
    $this->amount = $amount;
  }

  public function getAmount () {
    return $this->amount;
  }

  public function setCurrency ($currency) {
    $this->currency = $currency;
  }

  public function getCurrency () {
    return $this->currency;
  }

  public function setPluginName ($pluginName) {
    $this->pluginName = $pluginName;
  }

  public function getPluginName () {
    return $this->pluginName;
  }

  public function setPluginProperties ($pluginProperties) {
    $this->pluginProperties = $pluginProperties;
  }

  public function getPluginProperties () {
    return $this->pluginProperties;
  }

  public function setAuditLogs ($auditLogs) {
    $this->auditLogs = $auditLogs;
  }

  public function getAuditLogs () {
    return $this->auditLogs;
  }

}
