<?php

/*
 * Copyright 2011-2017 Ning, Inc.
 * Copyright 2014 Groupon, Inc.
 * Copyright 2014 The Billing Project, LLC
 *
 * The Billing Project licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
namespace Killbill\Client\Type;


/*
 *                       DO NOT EDIT!!!
 *    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)
 */


class ProductAttributes extends \Killbill\Client\Resource {
  protected $type = null;
  protected $name = null;
  protected $plans = null;
  protected $included = null;
  protected $available = null;

  public function setType ($type) {
    $this->type = $type;
  }

  public function getType () {
    return $this->type;
  }

  public function setName ($name) {
    $this->name = $name;
  }

  public function getName () {
    return $this->name;
  }

  public function setPlans ($plans) {
    $this->plans = $plans;
  }

  public function getPlans () {
    return $this->plans;
  }

  public function setIncluded ($included) {
    $this->included = $included;
  }

  public function getIncluded () {
    return $this->included;
  }

  public function setAvailable ($available) {
    $this->available = $available;
  }

  public function getAvailable () {
    return $this->available;
  }

}
