<?php

/*
 * Copyright 2011-2017 Ning, Inc.
 * Copyright 2014 Groupon, Inc.
 * Copyright 2014 The Billing Project, LLC
 *
 * The Billing Project licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
namespace Killbill\Client\Type;


/*
 *                       DO NOT EDIT!!!
 *    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)
 */


class TierAttributes extends \Killbill\Client\Resource {
  protected $tiers = null;
  protected $limits = null;
  protected $fixedPrice = null;
  protected $recurringPrice = null;

  public function setTiers ($tiers) {
    $this->tiers = $tiers;
  }

  public function getTiers () {
    return $this->tiers;
  }

  public function setLimits ($limits) {
    $this->limits = $limits;
  }

  public function getLimits () {
    return $this->limits;
  }

  public function setFixedPrice ($fixedPrice) {
    $this->fixedPrice = $fixedPrice;
  }

  public function getFixedPrice () {
    return $this->fixedPrice;
  }

  public function setRecurringPrice ($recurringPrice) {
    $this->recurringPrice = $recurringPrice;
  }

  public function getRecurringPrice () {
    return $this->recurringPrice;
  }

}
